# https://mdformat.readthedocs.io/en/stable/users/configuration_file.html
wrap = 79            # possible values: {"keep", "no", INTEGER}
number = true        # possible values: {false, true}
end_of_line = "crlf" # possible values: {"lf", "crlf"}
