exclude: '^(\.tox|\.env|dist|\.vscode)(/|$)'
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-alfred,
            flake8-broken-line,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-eradicate,
            flake8-functions,
            flake8-functions-names,
            flake8-printf-formatting,
            flake8-pytest-style,
            flake8-simplify,
            pep8-naming,
            flake8-cognitive-complexity,
            flake8-expression-complexity,
          ]

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place, --docstring-length, "75", "75"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      # - id: check-yaml
      # - id: check-toml
      # - id: check-json
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: [--branch, master, --branch, master]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
