site_name: Optmath docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indygo
      accent: indygo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Development:
    - Basic Tox: "develop/basic_tox.md"
    - Common tools: "develop/common.md"
    - Python code: "develop/python.md"
    - C/C++ extensions: "develop/c_extension.md"
  - Changelog: changelog.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - macros:
      include_dir:
        .
