# https://black.readthedocs.io/en/stable/
[tool.black]
line-length = 79
target-version = ['py310']
extend-exclude = [
    "external",
    ".tox",
    ".eggs",
    "build",
    "dist",
    "typing",
    ".temp",
]

[build-system]
requires = ["setuptools", "wheel", "Cython"]
