from typing import List

class Index:
    def __init__(self, _index: List[int]) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: "Index") -> bool:
        raise TypeError
        ...
    def __ne__(self, other: "Index") -> bool:
        raise TypeError
        ...
