class PyRectangle:

    x0: int
    y0: int
    x1: int
    y1: int

    def __init__(self, x0: int, y0: int, x1: int, y1: int) -> None: ...
    def get_area(self) -> float: ...
    def get_size(self) -> float: ...
    def move(self, dx: int, dy: int): ...

class PyThing:  # noqa: E302

    x0: int
    y0: int
    x1: int
    y1: int

    def __init__(self, x0: int, y0: int, x1: int, y1: int) -> None: ...
    def get_area(self) -> float: ...
    def get_size(self) -> float: ...
    def move(self, dx: int, dy: int): ...
