name: Test suite on Windows

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
  workflow_dispatch: {}

jobs:
  python_test_suite:
    strategy:
      matrix:
        python_version: ["3.7.12", "3.8.12", "3..12", "3.10.3"]
        os: [ubuntu-latest, windows-latest]
        include:
          - tox_env: "37"
            python_version: "3.7.12"
          - tox_env: "38"
            python_version: "3.8.12"
          - tox_env: "39"
            python_version: "3.9.12"
          - tox_env: "310"
            python_version: "3.10.3"
      max-parallel: 1
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout optmath and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Chocolately and LLVM
      uses: crazy-max/ghaction-chocolatey@v1.7.0
      with:
        args: install llvm

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: pip

    - name: Install tox
      run: python -m pip install tox

    - name: Build release binaries of C++ extension
      run: tox -e cmake -vv -- --clean -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        architecture: "x64"
        cache: pip

    - name: Run Python test suite
      run: tox -e py${{ matrix.tox_env }} -vv

  cpp_and_static_tests_windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Checkout optmath and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Chocolately and LLVM
      uses: crazy-max/ghaction-chocolatey@v1.7.0
      with:
        args: install llvm

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: pip

    - name: Install tox
      run: python -m pip install tox

    - name: Run C++ test suite
      run: tox -e googletest -vv -- -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Run static typechecking on Python code
      run: tox -e mypy -vv

  cpp_and_static_tests_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout optmath and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install LLVM
      run: sudo apt install clang

    - name: Set up Python interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: pip

    - name: Install tox
      run: python -m pip install tox

    - name: Run C++ test suite
      run: tox -e googletest -vv -- -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Run static typechecking on Python code
      run: tox -e mypy -vv
