name: Test suite on Windows

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
    - name: Checkout optmath and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Chocolately and LLVM
      uses: crazy-max/ghaction-chocolatey@v1.7.0
      with:
        args: install llvm

    - name: Set up Python 3.7 interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
        architecture: "x64"
        cache: pip

    - name: Set up Python 3.8 interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        architecture: "x64"
        cache: pip

    - name: Set up Python 3.9 interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        architecture: "x64"
        cache: pip

    - name: Set up Python 3.10 interpreter
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        architecture: "x64"
        cache: pip

    - name: Install tox
      run: python -m pip install tox

    - name: Run C++ and Python test suite with tox
      run: tox
